insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'Daniel Dakar', 'nostalgic and enchanting childhood adventure', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 9, 'Daniel Dakar', 'nostalgic and enchanting childhood adventure', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 10, 'Daniel Dakar', 'nostalgic and enchanting childhood adventure', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'Daniel Dakar', 'nostalgic and enchanting childhood adventure', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 9, 'Daniel Dakar', 'nostalgic and enchanting childhood adventure', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 9, 'Daniel Dakar', 'nostalgic and enchanting childhood adventure', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'Daniel Dakar', 'immersive fantasy that redefined the genre', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'Daniel Dakar', 'immersive fantasy that redefined the genre', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'Daniel Dakar', 'immersive fantasy that redefined the genre', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'Daniel Dakar', 'classic sports drama that still resonates today', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'Daniel Dakar', 'classic sports drama that still resonates today', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 7, 'Daniel Dakar', 'classic sports drama that still resonates today', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 7, 'Daniel Dakar', 'classic sports drama that still resonates today', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 6, 'Daniel Dakar', 'classic sports drama that still resonates today', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 8, 'Daniel Dakar', 'memorable performance by Johnny Depp though divisive', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 9, 'Daniel Dakar', 'dark, haunting, and masterfully directed by Scorsese', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 6, 'Daniel Dakar', ' Indiana  yet one movie too much', null);  # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7164, 8, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7164 Adventures of Young Indiana Jones: Adventures in the Secret Service 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7165, 9, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7165 Adventures of Young Indiana Jones: Daredevils of the Desert 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7166, 8, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7166 Adventures of Young Indiana Jones: Masks of Evil 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7167, 9, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7167 Adventures of Young Indiana Jones: Oganga, the Giver and Taker of Life 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7168, 7, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7168 Adventures of Young Indiana Jones: Spring Break Adventure 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7169, 8, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7169 Adventures of Young Indiana Jones: Tales of Innocence 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7170, 8, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7170 Adventures of Young Indiana Jones: The Phantom Train of Doom 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7171, 9, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 7171 Adventures of Young Indiana Jones: The Trenches of Hell 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159168, 8, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159168 Indiana Jones Adventures: The Ride 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159169, 8, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159169 Indiana Jones and the Emperor's Tomb 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159170, 9, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159170 Indiana Jones and the Fate of Atlantis 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159171, 7, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159171 Indiana Jones and the Infernal Machine 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 7, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159173, 7, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159173 Indiana Jones and the Last Crusade (1989/II) 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159176, 9, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159176 Indiana Jones' Greatest Adventures 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'Daniel Dakar', 'Comic action,  Harrison Ford, George Lucas', null);  # 159175 Adventures of Young Indiana Jones: The Phantom Train of Doom 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313464, 8, 'Daniel Dakar', 'fast-paced space combat with iconic starfighters', null);  # 313464 Star Wars Rogue Leader: Rogue Squadron 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313465, 8, 'Daniel Dakar', 'varied missions mixing ground and space battles', null);  # 313465 Star Wars Rogue Squadron III: Rebel Strike 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313466, 8, 'Daniel Dakar', 'large-scale multiplayer battles set in the galaxy', null);  # 313466 Star Wars: Battlefront 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313467, 8, 'Daniel Dakar', 'bounty hunter tale with darker Star Wars tone', null);  # 313467 Star Wars: Bounty Hunter 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313468, 9, 'Daniel Dakar', 'classic shooter that introduced Star Wars FPS action', null);  # 313468 Star Wars: Dark Forces 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313469, 9, 'Daniel Dakar', 'vehicular combat spin-off with explosive fun', null);  # 313469 Star Wars: Demolition 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313480, 8, 'Daniel Dakar', 'real-time strategy experiment with mixed reviews', null);  # 313480 Star Wars: Force Commander 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313484, 7, 'Daniel Dakar', 'dark and challenging sequel blending Jedi and shooter', null);  # 313484 Star Wars: Jedi Knight - Dark Forces II 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313485, 8, 'Daniel Dakar', 'refined lightsaber combat with strong multiplayer', null);  # 313485 Star Wars: Jedi Knight - Jedi Academy 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313486, 7, 'Daniel Dakar', 'expansion adding depth and darker narrative', null);  # 313486 Star Wars: Jedi Knight - Mysteries of the Sith 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313487, 8, 'Daniel Dakar', 'cinematic storytelling with polished Jedi gameplay', null);  # 313487 Star Wars: Jedi Knight II - Jedi Outcast 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313488, 6, 'Daniel Dakar', 'fast-paced space battles with unique starfighters', null);  # 313488 Star Wars: Jedi Starfighter 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313489, 9, 'Daniel Dakar', 'legendary RPG with moral choices and rich story', null);  # 313489 Star Wars: Knights of the Old Republic 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313490, 5, 'Daniel Dakar', 'experimental fighting game with limited appeal', null);  # 313490 Star Wars: Masters of Ters Ksi 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (101704, 7, 'Daniel Dakar', 'ambitious tie-in game expanding the Matrix lore', null);  # 101704 Enter the Matrix 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337167, 10, 'Daniel Dakar', 'groundbreaking animation with heartwarming friendship', null);  # 337167 Toy Story 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337168, 9, 'Daniel Dakar', 'sequel that expanded humor and emotional depth', null);  # 337168 Toy Story 2 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199255, 8, 'Daniel Dakar', 'fun animal adventure with strong comedic moments', null);  # 199255 Madagascar 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (55727, 8, 'Daniel Dakar', 'Pixar’s creative take on racing with heart and charm', null);  # 55727 Cars 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 9, 'Daniel Dakar', 'superhero family story mixing action and warmth', null);  # 158927 The Incredibles 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 9, 'Daniel Dakar', 'visually stunning ocean adventure with emotional core', null);  # 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215877, 8, 'Daniel Dakar', 'tense spy thriller with iconic stunts', null);  # 215877 Mission: Impossible 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215878, 6, 'Daniel Dakar', 'video game spin-off expanding IMF adventures', null);  # 215878 Mission: Impossible - Operation Surma 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 7, 'Daniel Dakar', 'stylized sequel with John Woo action flair', null);  # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'Daniel Dakar', 'Abrams’ darker take with emotional core', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177328, 8, 'Daniel Dakar', 'epic remake with groundbreaking visuals', null);  # 177328 King Kong 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 8, 'Daniel Dakar', 'redefined superhero genre for a new era', null);  # 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369459, 7, 'Daniel Dakar', 'ambitious sequel balancing many characters', null);  # 369459 X-Men 3 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369460, 6, 'Daniel Dakar', 'RPG spin-off game exploring mutant powers', null);  # 369460 X-Men Legends 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369461, 5, 'Daniel Dakar', 'behind-the-scenes scrapbook style feature', null);  # 369461 X-Men Production Scrapbook 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369462, 6, 'Daniel Dakar', 'arcade crossover with Street Fighter characters', null);  # 369462 X-Men vs. Street Fighter 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369463, 5, 'Daniel Dakar', 'classic arcade fighter introducing mutants', null);  # 369463 X-Men: Children of the Atom 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369464, 6, 'Daniel Dakar', 'console brawler with simple gameplay', null);  # 369464 X-Men: Mutant Academy 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369465, 6, 'Daniel Dakar', 'expanded sequel with more characters', null);  # 369465 X-Men: Mutant Academy 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369466, 5, 'Daniel Dakar', 'fighting game experiment with limited impact', null);  # 369466 X-Men: Next Dimension 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 9, 'Daniel Dakar', 'Raimi’s iconic superhero origin story', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'Daniel Dakar', 'emotional sequel with iconic villain Doc Ock', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 7, 'Daniel Dakar', 'ambitious but messy conclusion to Raimi’s trilogy', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311041, 6, 'Daniel Dakar', 'arcade-style spin-off Enter Electro', null);  # 311041 Spider-Man II: Enter Electro 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311042, 5, 'Daniel Dakar', 'TV-style low-budget Spider-Man outing', null);  # 311042 Spider-Man Strikes Back 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311043, 6, 'Daniel Dakar', 'comic-inspired Spider-Man vs Kingpin', null);  # 311043 Spider-Man vs. the Kingpin 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311044, 5, 'Daniel Dakar', 'animated Spider-Man battling Octopus', null);  # 311044 Spider-Man: Attack of the Octopus 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30953, 6, 'Daniel Dakar', 'campy take on the Caped Crusader', null);  # 30953 Batman & Robin 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30960, 7, 'Daniel Dakar', 'futuristic animated spin on Batman', null);  # 30960 Batman Beyond 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 8, 'Daniel Dakar', 'dark animated feature with Joker’s return', null);  # 30961 Batman Beyond: Return of the Joker 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30975, 6, 'Daniel Dakar', 'racing spin-off featuring Gotham’s hero', null);  # 30975 Batman: Gotham Racer 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313398, 6, 'Daniel Dakar', 'weaker entry but part of the saga', null);  # 313398 Star Trek V: The Final Frontier 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313399, 8, 'Daniel Dakar', 'political themes with strong character arcs', null);  # 313399 Star Trek VI: The Undiscovered Country 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313395, 7, 'Daniel Dakar', 'search for Spock brings emotional depth', null);  # 313395 Star Trek III: The Search for Spock 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313396, 8, 'Daniel Dakar', 'time travel adventure with humor and heart', null);  # 313396 Star Trek IV: The Voyage Home 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (227823, 7, 'Daniel Dakar', 'anime fighter with exciting ninja battles', null);  # 227823 Naruto: Gekitou ninja taisen! 2 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398997, 6, 'Daniel Dakar', 'classic shonen introduction to Naruto world', null);  # 398997 Naruto 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120117, 7, 'Daniel Dakar', 'slasher icon Jason’s bloody debut', null);  # 120117 Friday the 13th 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120119, 6, 'Daniel Dakar', 'continuation that builds the mythos', null);  # 120119 Friday the 13th Part 2 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120120, 6, 'Daniel Dakar', '3D gimmick adds novelty to the kills', null);  # 120120 Friday the 13th Part 3: 3D 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120121, 7, 'Daniel Dakar', 'Jason fully revived in supernatural twist', null);  # 120121 Friday the 13th Part VI: Jason Lives 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120122, 6, 'Daniel Dakar', 'slasher formula continues with new victims', null);  # 120122 Friday the 13th Part VII: The New Blood 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120123, 5, 'Daniel Dakar', 'Jason takes Manhattan in campy outing', null);  # 120123 Friday the 13th Part VIII: Jason Takes Manhattan 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120126, 6, 'Daniel Dakar', 'effective finale with shocking kills', null);  # 120126 Friday the 13th: The Final Chapter 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232455, 8, 'Daniel Dakar', 'fan-favorite with memorable dream warriors', null);  # 232455 A Nightmare on Elm Street 3: Dream Warriors 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232456, 7, 'Daniel Dakar', 'Freddy dominates in creative dream kills', null);  # 232456 A Nightmare on Elm Street 4: The Dream Master 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232457, 6, 'Daniel Dakar', 'Freddy’s revenge adds darker tone', null);  # 232457 A Nightmare on Elm Street Part 2: Freddy’s Revenge 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232458, 9, 'Daniel Dakar', 'horror classic that introduced Freddy Krueger', null);  # 232458 A Nightmare on Elm Street 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232459, 6, 'Daniel Dakar', 'TV-style continuation with Freddy’s return', null);  # 232459 A Nightmare on Elm Street 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232460, 6, 'Daniel Dakar', 'the dream child continues surreal horror', null);  # 232460 A Nightmare on Elm Street: The Dream Child 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'Daniel Dakar', 'Tom Cruise play - amazing!', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 6, 'Daniel Dakar', 'Iconic Julia Roberts play', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 5, 'Daniel Dakar', 'Brad Pitt & Angelina Jolie spy play', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 8, 'Daniel Dakar', 'Bond film with a mix of intrigue, romance, and danger', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 8, 'Daniel Dakar', 'Bond film with a mix of intrigue, romance, and danger', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 7, 'Daniel Dakar', 'Bond film with a mix of intrigue, romance, and danger', null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 9, 'Daniel Dakar', 'Bond film with a mix of intrigue, romance, and danger', null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 7, 'Daniel Dakar', 'Bond film with a mix of intrigue, romance, and danger', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 8, 'Daniel Dakar', 'Bond film with a mix of intrigue, romance, and danger', null);  # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 7, 'Daniel Dakar', 'Bond film with a mix of intrigue, romance, and danger', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 6, 'Daniel Dakar', 'charming and exciting to see every time', null);  # 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (50639, 7, 'Daniel Dakar', 'dark but very good movie', null);  # 50639 Butterfly Effect, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86278, 8, 'Daniel Dakar', 'tight hostage-thriller with sharp one-liners', null);  # 86278 Die Hard 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86279, 8, 'Daniel Dakar', 'snowbound sequel that escalates the chaos', null);  # 86279 Die Hard 2 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188508, 6, 'Daniel Dakar', 'buddy-cop chemistry with gritty action', null);  # 188508 Lethal Weapon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 9, 'Daniel Dakar', 'bigger stakes and sharper banter', null);  # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 8, 'Daniel Dakar', 'third round blending humor and heart', null);  # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 9, 'Daniel Dakar', 'veteran partnership facing modern threats', null);  # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271820, 9, 'Daniel Dakar', 'brutal survival action with raw intensity', null);  # 271820 Rambo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271823, 8, 'Daniel Dakar', 'Soviet-era showdown with explosive set pieces', null);  # 271823 Rambo III 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199208, 9, 'Daniel Dakar', 'post-apocalyptic grit and road mayhem', null);  # 199208 Mad Max 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199209, 8, 'Daniel Dakar', 'lean, ferocious sequel redefining action', null);  # 199209 Mad Max 2: The Road Warrior 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199210, 6, 'Daniel Dakar', 'comic-book spectacle with wasteland flair', null);  # 199210 Mad Max Beyond Thunderdome 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199211, 9, 'Daniel Dakar', 'relentless chase opera with visionary craft', null);  # 199211 Mad Max: Fury Road 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199212, 6, 'Daniel Dakar', 'retrospective feature for franchise context', null);  # 199212 Mad Max: The Film Phenomenon 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (364709, 6, 'Daniel Dakar', 'dark anthology with cult-leaning stories', null);  # 364709 Wicked 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (364710, 6, 'Daniel Dakar', 'second volume expanding the macabre tone', null);  # 364710 Wicked Anthology: Volume 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10833, 5, 'Daniel Dakar', 'offbeat spin using alien tropes for laughs', null);  # 10833 Alien 51 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10834, 5, 'Daniel Dakar', 'low-budget curiosum for franchise collectors', null);  # 10834 Alien 8 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (262646, 8, 'Daniel Dakar', 'jungle hunt blending horror and machismo', null);  # 262646 Predator 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (262647, 7, 'Daniel Dakar', 'urban sequel with relentless cat-and-mouse', null);  # 262647 Predator 2 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (262648, 6, 'Daniel Dakar', 'game-world take on the Yautja mythos', null);  # 262648 Predator: Concrete Jungle 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10935, 8, 'Daniel Dakar', 'cross-franchise clash with tactical action', null);  # 10935 Aliens Vs. Predator 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10936, 6, 'Daniel Dakar', 'expanded sequel with refined mechanics', null);  # 10936 Aliens vs. Predator 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10937, 7, 'Daniel Dakar', 'story add-on deepening the AVP conflict', null);  # 10937 Aliens vs. Predator 2: Primal Hunt 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 8, 'Daniel Dakar', 'family & funny movie', null);  # 218415 Monsters, Inc. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 5, 'Daniel Dakar', 'fairy-tale satire with big heart', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 5, 'Daniel Dakar', 'sequel with sharper humor and emotional depth', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300232, 5, 'Daniel Dakar', 'royal chaos with pop-culture parody', null);  # 300232 Shrek 3 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 5, 'Daniel Dakar', 'short 4D adventure that expands the world', null);  # 300233 Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 5, 'Daniel Dakar', 'slick ensemble heist full of charm', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 5, 'Daniel Dakar', 'playful European caper with style', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 5, 'Daniel Dakar', 'buddy sci-fi comedy with stylish aliens', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210740, 5, 'Daniel Dakar', 'interactive ride film with humor and action', null);  # 210740 Men in Black Alien Attack 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210741, 5, 'Daniel Dakar', 'bigger sequel introducing new villains', null);  # 210741 Men in Black II 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 5, 'Daniel Dakar', 'powerful prison drama about hope and resilience', null);  # 297838 The Shawshank Redemption 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333656, 5, 'Daniel Dakar', 'epic romance anchored by spectacle', null);  # 333656 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 5, 'Daniel Dakar', 'neo-noir puzzle told in reverse', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257291, 5, 'Daniel Dakar', 'documentary showcasing Earth’s oceans', null);  # 257291 Planet Ocean 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289558, 9, 'Daniel Dakar', 'raw rise-and-fall of a gangster empire', null);  # 289558 Scarface 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (138797, 7, 'Daniel Dakar', 'sports comedy blending absurdity with charm', null);  # 138797 Happy Gilmore 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (969, 10, 'Daniel Dakar', 'masterclass in dialogue and moral tension', null);  # 969 12 Angry Men 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 10, 'Daniel Dakar', 'epic life journey mixing humor and tragedy', null);  # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 9, 'Daniel Dakar', 'provocative look at truth and perception', null);  # 340901 Truman Show, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 7, 'Daniel Dakar', 'cult classic with eccentric characters', null);  # 37178 Big Lebowski 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351705, 7, 'Daniel Dakar', 'stylish revenge thriller with dark tones', null);  # 351705 Vengeance 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 10, 'Daniel Dakar', 'psychological dive into chaos of war', null);  # 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 9, 'Daniel Dakar', 'moving prison tale about humanity', null);  # 134077 Green Mile, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 8, 'Daniel Dakar', 'cartoonish energy elevated by Carrey', null);  # 207157 Mask, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 8, 'Daniel Dakar', 'intense horror fueled by isolation', null);  # 299073 Shining, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 9, 'Daniel Dakar', 'operatic mafia saga of loyalty and betrayal', null);  # 130128 Godfather, The 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66286, 10, 'Daniel Dakar', 'uplifting sports drama with grit', null);  # 66286 Coach Carter 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254986, 9, 'Daniel Dakar', 'harrowing survival anchored by performance', null);  # 254986 Pianist, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'Daniel Dakar', 'spy adventure with exotic spectacle', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56373, 6, 'Daniel Dakar', 'light family fantasy with gentle charm', null);  # 56373 Casper 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 10, 'Daniel Dakar', 'stylized martial arts saga with poetic violence', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289787, 9, 'Daniel Dakar', 'moving drama anchored by Pacino’s performance', null);  # 289787 Scent of a Woman 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 5, 'Daniel Dakar', 'dark superhero reinvention with gothic tone', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 8, 'Daniel Dakar', 'Tarantino twist on WWII with sharp dialogue', null);  # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 8, 'Daniel Dakar', 'lighthearted rom-com with witty charm', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166917, 9, 'Daniel Dakar', 'emotional sports drama mixing love and ambition', null);  # 166917 Jerry Maguire 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 5, 'Daniel Dakar', 'origin story with grounded realism', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40187, 9, 'Daniel Dakar', 'stylish vampire action blending horror and thrills', null);  # 40187 Blade 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 8, 'Daniel Dakar', 'dark exploration of consumerism and identity', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 5, 'Daniel Dakar', 'gothic sequel with Burton’s signature touch', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26846, 8, 'Daniel Dakar', 'funny, clever continuation of time-travel tale', null);  # 26846 Back to the Future Part II 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 10, 'Daniel Dakar', 'Tarantino’s stylish revenge epic with iconic fights', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'Daniel Dakar', 'campy superhero installment with colorful villains', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 7, 'Daniel Dakar', 'gritty mob story with De Niro and Pesci', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (87280, 8, 'Daniel Dakar', 'romantic classic with unforgettable dance scenes', null);  # 87280 Dirty Dancing 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 7, 'Daniel Dakar', 'powerful historical drama by Spielberg', null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'Daniel Dakar', 'intense thriller with nonstop suspense', null);  # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155213, 10, 'Daniel Dakar', 'brilliantly written animated adventure', null);  # 155213 Ice Age 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41849, 5, 'Daniel Dakar', 'romantic survival drama with uneven acting', null);  # 41849 Blue Lagoon, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2709, 8, 'Daniel Dakar', 'lighthearted rom-com with goofy humor', null);  # 2709 50 First Dates 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148200, 9, 'Daniel Dakar', 'family holiday favorite with timeless charm', null);  # 148200 Home Alone 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (79716, 7, 'Daniel Dakar', 'solid disaster action with great visuals', null);  # 79716 Day After Tomorrow 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 6, 'Daniel Dakar', 'Spielberg’s iconic shark horror', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 8, 'Daniel Dakar', 'witty romantic comedy classic', null);  # 362808 When Harry Met Sally... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (108760, 5, 'Daniel Dakar', 'forgettable superhero attempt', null);  # 108760 Fantastic Four 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'Daniel Dakar', 'engaging sci-fi disaster with strong visuals', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'Daniel Dakar', 'timeless animated masterpiece with heart', null);  # 191246 Lion King, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30647, 8, 'Daniel Dakar', 'stylish thriller with iconic moments', null);  # 30647 Basic Instinct 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 9, 'Daniel Dakar', 'emotional story about resilience and genius', null);  # 32114 Beautiful Mind 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309634, 7, 'Daniel Dakar', 'classic musical though not my favorite', null);  # 309634 Sound of Music 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258860, 7, 'Daniel Dakar', 'thrilling mix of extreme sports and crime', null);  # 258860 Point Break 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279841, 8, 'Daniel Dakar', 'satirical sci-fi with strong action', null);  # 279841 RoboCop 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37002, 7, 'Daniel Dakar', 'lighthearted comedy with surprising warmth', null);  # 37002 Big Daddy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 10, 'Daniel Dakar', 'gritty war film with unforgettable acting', null);  # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112205, 8, 'Daniel Dakar', 'colorful sci-fi with nonstop excitement', null);  # 112205 Fifth Element 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222339, 7, 'Daniel Dakar', 'fast-paced adventure with humor and action', null);  # 222339 Mummy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272644, 9, 'Daniel Dakar', 'fun and funny, family movie', null);  # 272644 Ratatouille 2006
