




insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379290, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 379290 Adventures of Batman, The 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379327, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 379327 Adventures of Robin Hood, The 1955
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379331, 7, 'Noy Nizri', 'Classic detective storytelling', null);  # 379331 Adventures of Sherlock Holmes, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 6, 'Noy Nizri', 'Cool nostalgic 2000s comic', null);  # 381392 Batman Beyond 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (383395, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 383395 Captain America 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (393012, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 393012 Iron Man 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (405119, 3, 'Noy Nizri', 'Outdated style and boring plot', null);  # 405119 Sherlock Holmes 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406158, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 406158 Spider-Man 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13343, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 13343 Amazing Adventures of Spider-Man, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 9, 'Noy Nizri', 'Funny and teen-relatable movie', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 5, 'Noy Nizri', 'Classic heroic action', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30951, 5, 'Noy Nizri', 'Classic heroic action', null);  # 30951 Batman & Mr. Freeze: SubZero 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 6, 'Noy Nizri', 'Classic heroic action', null);  # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30953, 6, 'Noy Nizri', 'Classic heroic action', null);  # 30953 Batman & Robin 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30957, 2, 'Noy Nizri', 'Outdated style and quality', null);  # 30957 Batman and Robin 1949
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 8, 'Noy Nizri', 'Classic heroic action, more modern', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 8, 'Noy Nizri', 'Classic heroic action, more modern', null);  # 30961 Batman Beyond: Return of the Joker (2000/I) 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30962, 8, 'Noy Nizri', 'Classic heroic action, more modern', null);  # 30962 Batman Beyond: The Movie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 4, 'Noy Nizri', 'Outdated style and quality', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 4, 'Noy Nizri', 'Outdated style and quality', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30968, 4, 'Noy Nizri', 'Outdated style and quality', null);  # 30968 Batman Returns (1992/II) 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30970, 2, 'Noy Nizri', 'Outdated style and quality', null);  # 30970 Batman/Superman Movie, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30972, 2, 'Noy Nizri', 'Outdated style and slow plot', null);  # 30972 Batman: Dark Justice 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30974, 5, 'Noy Nizri', 'Classic heroic but outdated', null);  # 30974 Batman: Dead End 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30975, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 30975 Batman: Gotham Racer 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30977, 3, 'Noy Nizri', 'Outdated style and quality', null);  # 30977 Batman: Mystery of the Batwoman 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 6, 'Noy Nizri', 'Engaging adventure movie', null);  # 32180 Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 7, 'Noy Nizri', 'Classic sci-fi action', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 6, 'Noy Nizri', 'Detective-style action movie', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 9, 'Noy Nizri', 'Popular action franchise', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 9, 'Noy Nizri', 'Iconic psychological thriller with depth', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139651, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 139651 Harry Potter and the Chamber of Secrets (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 6, 'Noy Nizri', 'Light romantic comedy', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 7, 'Noy Nizri', 'Action-packed adventure sequel', null);  # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 7, 'Noy Nizri', 'Action-packed adventure sequel', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 7, 'Noy Nizri', 'Action-packed adventure sequel', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 6, 'Noy Nizri', 'Classic beloved superhero', null);  # 162380 Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 8, 'Noy Nizri', 'Classic horror-action thriller', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'Noy Nizri', 'Epic historical action drama', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'Noy Nizri', 'Beloved animated kids movie', null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194492, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194492 Lord of the Rings 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194495, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194495 Lord of the Rings: Return of the King, The (2003/II) 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194498, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194498 Lord of the Rings: The Fellowship of the Ring, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194499, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194499 Lord of the Rings: The Quest Fulfilled, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194503, 9, 'Noy Nizri', 'Popular fantasy film series', null);  # 194503 Lord of the Rings: The Two Towers, The (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 9, 'Noy Nizri', 'Sci-fi action-comedy classic', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 9, 'Noy Nizri', 'Classic sports sequel franchise', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 9, 'Noy Nizri', 'Classic sports sequel franchise', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 9, 'Noy Nizri', 'Classic sports sequel franchise', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 9, 'Noy Nizri', 'Classic sports sequel franchise', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 9, 'Noy Nizri', 'Classic sports sequel franchise', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 3, 'Noy Nizri', 'Outdated animation style', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 3, 'Noy Nizri', 'Outdated animation style', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 5, 'Noy Nizri', 'Classic beloved superhero film', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 5, 'Noy Nizri', 'Classic beloved superhero film', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 5, 'Noy Nizri', 'Classic beloved superhero film', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 6, 'Noy Nizri', 'Family spy adventure franchise', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 6, 'Noy Nizri', 'Family spy adventure franchise', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 6, 'Noy Nizri', 'Family spy adventure franchise', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 7, 'Noy Nizri', 'Classic superhero origin film', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'Noy Nizri', 'Classic superhero origin film', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 10, 'Noy Nizri', 'Epic romantic historical drama', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 6, 'Noy Nizri', 'Beloved Pixar animated film', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'Noy Nizri', 'Epic historical action drama', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 8, 'Noy Nizri', 'Thought‑provoking religious drama', null);  -- Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185957, 5, 'Noy Nizri', 'Low-profile mystery adventure', null);  -- Latitude Zero 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188427, 4, 'Noy Nizri', 'Music-themed documentary with niche appeal', null);  -- Let's Rock Again! 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 9, 'Noy Nizri', 'Iconic buddy cop action sequel franchise', null);  -- Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 9, 'Noy Nizri', 'Iconic buddy cop action sequel franchise', null);  -- Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 9, 'Noy Nizri', 'Iconic buddy cop action sequel franchise', null);  -- Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 9, 'Noy Nizri', 'Iconic buddy cop action sequel franchise', null);  -- Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 9, 'Noy Nizri', 'International spy action sequel franchise', null);  -- Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 9, 'Noy Nizri', 'International spy action sequel franchise', null);  -- Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (315645, 8, 'Noy Nizri', 'Raw and stylish crime classic with sharp dialogue and tension', null);  -- Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279594, 5, 'Noy Nizri', 'Simple low-budget crime drama', null);  -- Robbers 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283196, 4, 'Noy Nizri', 'Unremarkable plot with minimal character development', null);  -- Rules, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (288493, 4, 'Noy Nizri', 'Old-school horror with dated effects and atmosphere', null);  -- Satanic Rites of Dracula, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289646, 3, 'Noy Nizri', 'Low-budget obscure crime drama', null);  -- Scarmour 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 7, 'Noy Nizri', 'Psychological thriller with strong performances and suspense', null);  -- Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310168, 4, 'Noy Nizri', 'Mediocre space documentary with limited narrative appeal', null);  -- Space Station 3D 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 9, 'Noy Nizri', 'Fast-paced and entertaining con-man drama based on true events', null);  -- Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 7, 'Noy Nizri', 'Tense psychological thriller with great performances', null);  -- Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 6, 'Noy Nizri', 'Dark and atmospheric medical drama', null);  -- Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 7, 'Noy Nizri', 'Compelling true-crime drama with strong lead performance', null);  -- Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 9, 'Noy Nizri', 'Emotional and visually striking drama with a unique narrative concept', null);  -- Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 6, 'Noy Nizri', 'Biographical drama with a poetic tone', null);  -- Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65522, 6, 'Noy Nizri', 'Slow-paced drama with solid performances and emotional tension', null);  -- Clearing, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65621, 5, 'Noy Nizri', 'Classic 80s action with suspenseful mountain setting', null);  -- Cliff Hanger 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 6, 'Noy Nizri', 'Political action thriller', null);  # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74133, 3, 'Noy Nizri', 'Low-budget indie drama', null);  # 74133 Crutch 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78877, 2, 'Noy Nizri', 'Outdated horror with weak plot', null);  # 78877 Dark Mist, The 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (79845, 5, 'Noy Nizri', 'Classic western action', null);  # 79845 Day of the Evil Gun 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176749, 4, 'Noy Nizri', 'Political drama with a slow pace', null);  # 176749 Kill the Messenger 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183837, 2, 'Noy Nizri', 'Low production martial arts', null);  # 183837 Lady Warriors 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'Noy Nizri', 'Action-comedy with strong cast', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 9, 'Noy Nizri', 'Popular heist film franchise', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 8, 'Noy Nizri', 'Popular heist film franchise', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258874, 3, 'Noy Nizri', 'Low-budget teen drama', null);  # 258874 Point Five 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 6, 'Noy Nizri', 'Dark psychological thriller', null);  # 258948 Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263443, 2, 'Noy Nizri', 'Historical documentary with limited appeal', null);  # 263443 Price for Peace 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (265273, 2, 'Noy Nizri', 'Sci-fi mystery with poor execution', null);  # 265273 Prodigy, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 9, 'Noy Nizri', 'Adventure classic, iconic franchise', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 5, 'Noy Nizri', 'Romantic thriller with suspenseful edge', null);  # 308025 Someone to Watch Over Me 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 8, 'Noy Nizri', 'British crime comedy with sharp dialogue', null);  # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308057, 3, 'Noy Nizri', 'Early horror attempt, dated presentation', null);  # 308057 Something Evil 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335592, 2, 'Noy Nizri', 'Low-quality TV drama', null);  # 335592 Too Good to Be True (1997/I) 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363902, 4, 'Noy Nizri', 'Social commentary film with limited cinematic impact', null);  # 363902 White Like Me 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368865, 6, 'Noy Nizri', 'Insightful wrestling documentary for fans of the genre', null);  # 368865 Wrestling with Shadows 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (374517, 4, 'Noy Nizri', 'Obscure thriller with low production value', null);  # Zenith 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105851, 4, 'Noy Nizri', 'Unusual comedy with mixed reviews', null);  # Exit to Eden 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116829, 4, 'Noy Nizri', 'Short drama with limited impact', null);  # Foot Shooting Party, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 7, 'Noy Nizri', 'Classic spy action from the James Bond franchise', null);  # For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 6, 'Noy Nizri', 'Romantic drama with strong performances', null);  # Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'Noy Nizri', 'Epic historical action film with powerful storytelling', null);  # Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129887, 6, 'Noy Nizri', 'Thai football drama with youthful energy', null);  # Goal Club 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 6, 'Noy Nizri', 'Romantic comedy with charming leads', null);  # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203481, 5, 'Noy Nizri', 'Classic horror with vintage feel', null);  # 203481 Man Who Could Cheat Death, The 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207645, 3, 'Noy Nizri', 'Obscure low-budget thriller', null);  # 207645 Matanza 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 7, 'Noy Nizri', 'Scorsese’s gritty crime drama with early De Niro', null);  # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (212104, 4, 'Noy Nizri', 'Indie drama with a niche audience', null);  # 212104 Metropolitan 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232019, 4, 'Noy Nizri', 'Low-budget horror with limited reach', null);  # 232019 Night of a Thousand Screams 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238658, 3, 'Noy Nizri', 'Obscure indie thriller with little impact', null);  # 238658 Offering, The 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (242530, 3, 'Noy Nizri', 'Low-profile thriller with limited reach', null);  # 242530 Open Season 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245183, 3, 'Noy Nizri', 'Little-known drama with minimal exposure', null);  # 245183 Out of the Rain 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247849, 3, 'Noy Nizri', 'Obscure film with niche audience', null);  # 247849 Pantalones 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (277703, 3, 'Noy Nizri', 'Minimal data available; likely a low-budget release', null);  # 277703 Richard Roe 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 6, 'Noy Nizri', 'Holiday comedy with Bill Murray’s charm', null);  # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297032, 5, 'Noy Nizri', 'Punjabi biopic with regional significance', null);  # 297032 Shaheed-E-Mohabbat 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302296, 3, 'Noy Nizri', 'Experimental short with philosophical themes', null);  # 302296 Simulacra 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (334747, 4, 'Noy Nizri', 'Indie drama with limited impact', null);  # 334747 Together & Alone 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 7, 'Noy Nizri', 'Bond sequel with memorable action', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 6, 'Noy Nizri', 'Biographical romantic drama with intense performances', null);  # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336555, 3, 'Noy Nizri', 'Obscure foreign drama with minimal impact', null);  # 336555 Toto leto doma 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (338478, 4, 'Noy Nizri', 'Workplace drama with limited appeal', null);  # 338478 Travail 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340271, 5, 'Noy Nizri', 'Documentary on homelessness with emotional weight', null);  # 340271 Trollywood 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350176, 2, 'Noy Nizri', 'Low-budget vampire film lacking substance', null);  # 350176 Vampire Brides 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350187, 2, 'Noy Nizri', 'Campy horror with poor execution', null);  # 350187 Vampire Hookers 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350189, 6, 'Noy Nizri', 'Anime cult classic for vampire lovers', null);  # 350189 Vampire Hunter D 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351705, 5, 'Noy Nizri', 'Standard revenge thriller with action elements', null);  # 351705 Vengeance 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359744, 3, 'Noy Nizri', 'Low-quality comedy with niche appeal', null);  # 359744 Washington Interns Gone Bad 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363633, 4, 'Noy Nizri', 'Indie psychological drama with uneven tone', null);  # 363633 Whirlpool, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (355356, 5, 'Noy Nizri', 'Interesting concept with artistic execution, but pacing issues', null);  # 355356 Visionary, The 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (682, 6, 'Noy Nizri', 'romantic comedy about growing up and searching for love', null);  # 682 100 Girls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1092, 6, 'Noy Nizri', 'Action-adventure with historical setting and cult appeal', null);  # 1092 13th Warrior, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1132, 5, 'Noy Nizri', 'Period drama with modest emotional depth and limited reach', null);  # 1132 15 Amore 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1191, 5, 'Noy Nizri', 'Indie teen crime drama with gritty but limited execution', null);  # 1191 17 and Under 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1529, 8, 'Noy Nizri', 'High-octane action sequel from the popular Fast & Furious franchise', null);  # 1529 2 Fast 2 Furious 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2092, 6, 'Noy Nizri', 'Indian prison drama with strong performances and social themes', null);  # 2092 3 Deewarein 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2690, 5, 'Noy Nizri', 'Classic 50s spy thriller with dated style', null);  # 2690 5 Steps to Danger 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2709, 8, 'Noy Nizri', 'Charming romantic comedy with heart and humor', null);  # 2709 50 First Dates 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192357, 5, 'Noy Nizri', 'Indie drama with limited reach and modest impact', null);  # 192357 Little White Boy 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (196522, 6, 'Noy Nizri', 'Light teen romantic comedy with simple charm', null);  # 196522 Lovewrecked 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (196588, 4, 'Noy Nizri', 'Obscure foreign drama with limited recognition', null);  # 196588 Lowcy skr 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (196995, 5, 'Noy Nizri', 'Crime comedy with amusing moments but mixed reviews', null);  # 196995 Lucky Numbers 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199192, 5, 'Noy Nizri', 'Classic 30s horror with gothic atmosphere, dated by modern standards', null);  # 199192 Mad Love 1935
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199243, 4, 'Noy Nizri', 'Low-profile indie thriller with limited impact', null);  # 199243 Mad Twin 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199463, 6, 'Noy Nizri', 'Indie crime comedy with witty banter and solid performances', null);  # 199463 Made 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203584, 6, 'Noy Nizri', 'Quirky Australian comedy-drama with satirical edge', null);  # 203584 Man Who Sued God, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203733, 5, 'Noy Nizri', 'Quirky Australian comedy with modest charm', null);  # 203733 Man's Gotta Do, A 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214090, 5, 'Noy Nizri', 'Experimental crime drama with artistic flair but mixed reception', null);  # 214090 Million Dollar Hotel, The 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214184, 7, 'Noy Nizri', 'Heartwarming British comedy-drama with charm and wit', null);  # 214184 Millions 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (219921, 4, 'Noy Nizri', 'Low-budget indie drama with emotional but limited appeal', null);  # 219921 Mother Ghost 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220982, 3, 'Noy Nizri', 'Obscure low-budget comedy with minimal recognition', null);  # 220982 Mr. Jinx 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222320, 2, 'Noy Nizri', 'Low-budget B-movie with weak plot and execution', null);  # 222320 Mummy Raider 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (224085, 6, 'Noy Nizri', 'Charming period family drama with biographical elements', null);  # 224085 My Life So Far 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (224186, 4, 'Noy Nizri', 'Low-profile indie drama with limited impact', null);  # 224186 My Neighbor's Daughter 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (224639, 7, 'Noy Nizri', 'Powerful indie drama with strong performances and emotional depth', null);  # 224639 Mysterious Skin 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (228317, 6, 'Noy Nizri', 'French comedy-drama with heartfelt and unconventional themes', null);  # 228317 Nationale 7 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230320, 4, 'Noy Nizri', 'Low-budget indie drama with minimal impact', null);  # 230320 Never Among Friends 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232146, 4, 'Noy Nizri', 'Indie drama with limited recognition and niche appeal', null);  # 232146 Night Out 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238871, 4, 'Noy Nizri', 'Low-profile indie comedy-drama with limited impact', null);  # 238871 Oh Boy! 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (239716, 4, 'Noy Nizri', 'Obscure indie drama with minimal recognition', null);  # 239716 Old Man Music 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (241830, 5, 'Noy Nizri', 'Indie drama tackling heavy themes with modest execution', null);  # 241830 One Week 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245646, 7, 'Noy Nizri', 'Funny and entertaining family animation from DreamWorks', null);  # 245646 Over the Hedge 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245661, 4, 'Noy Nizri', 'Obscure indie drama with limited recognition', null);  # 245661 Over the Mountains 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247492, 3, 'Noy Nizri', 'Low-budget sci-fi B-movie with poor execution', null);  # 247492 Pandora Machine 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303361, 3, 'Noy Nizri', 'Low-budget indie horror with limited appeal', null);  # 303361 Sitter's Night 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304527, 5, 'Noy Nizri', 'Light teen comedy with cultural clash humor', null);  # 304527 Slap Her... She's French 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304560, 6, 'Noy Nizri', 'Indie sports drama with strong performances and gritty tone', null);  # 304560 Slaughter Rule, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304570, 3, 'Noy Nizri', 'Low-budget underground horror with surreal exploitation style', null);  # 304570 Slaughterhouse of the Rising Sun 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304544, 4, 'Noy Nizri', 'Low-budget slasher horror with cult niche appeal', null);  # 304544 Slashers 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304552, 5, 'Noy Nizri', 'Classic 40s drama with aviation and romance themes', null);  # 304552 Slattery's Hurricane 1949
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304735, 3, 'Noy Nizri', 'Obscure experimental indie with surreal style', null);  # 304735 Sleep Always 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (305013, 5, 'Noy Nizri', 'Indie crime drama with modest impact and recognizable cast', null);  # 305013 Slingshot (2004/I) 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306223, 6, 'Noy Nizri', 'Lighthearted family comedy with sled dogs adventure', null);  # 306223 Snow Dogs 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (347346, 5, 'Noy Nizri', 'Indie war drama exploring post-war trauma with emotional depth', null);  # 347346 Unknown Soldier 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (358434, 4, 'Noy Nizri', 'Obscure indie drama with limited recognition', null);  # 358434 Wake 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359911, 4, 'Noy Nizri', 'Low-profile indie thriller with limited recognition', null);  # 359911 Watchful Eyes 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362753, 6, 'Noy Nizri', 'Jewish family comedy with quirky humor and mixed reviews', null);  # 362753 When Do We Eat? 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375834, 4, 'Noy Nizri', 'Dutch experimental indie drama with limited reach', null);  # 375834 Zoom - It's Always About Getting Closer 2000

